### PR TITLE
Allow Laravel 5.1

### PR DESCRIPTION
**Pull request by arthurkirkosa**

### CODE REVIEW

**Comment by nhowell** [comment]
+1

**Comment by seanthepottingshed** [comment]
+1

**Comment by thatislandguy** [comment]
Need this, it's keeping me from updating to 5.1.

**Comment by curser656** [comment]
+1

**Comment by cbraddoss** [comment]
+1

**Comment by nhowell** [comment]
@willvincent It would be nice to see this merged soon. :wink:

**Comment by willvincent** [comment]
Done. :+1: :)

**Comment by nhowell** [comment]
Thank you!

**Comment by nhowell** [comment]
@willvincent Would you be so kind to create a new release (e.g. 1.0.3) on Packagist, too?

**Comment by willvincent** [comment]
Sure.. it's there. :)

**Comment by nhowell** [comment]
Much appreciated! :+1:

**Pull request merged**
